apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 86.2.3
    helm:
      values: |
        # Enable all major components
        grafana:
          enabled: true
          adminPassword: "admin123"
          persistence:
            enabled: true
            storageClassName: "ebs-gp3"
            size: 10Gi
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "ebs-gp3"
                  resources:
                    requests:
                      storage: 10Gi
            # Important: Allows Prometheus Operator to see your custom rules
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: "ebs-gp3"
                  resources:
                    requests:
                      storage: 10Gi
      
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  # Critical for kube-prometheus-stack to avoid sync loops with generated webhooks
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true