# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-application
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://prometheus-community.github.io/helm-charts
#     chart: prometheus
#     targetRevision: 25.27.0 # You can update this to the latest version
#     helm:
#       values: |
#         alertmanager:
#           persistentVolume:
#             storageClass: "ebs-gp3"
#         server:
#           persistentVolume:
#             storageClass: "ebs-gp3"
      
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: prometheus
#   ignoreDifferences:
#     - group: apps
#       kind: StatefulSet
#       jqPathExpressions:
#         - .spec.volumeClaimTemplates[]?.apiVersion
#         - .spec.volumeClaimTemplates[]?.kind
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
#       - RespectIgnoreDifferences=true