apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Groundhog2k public community chart repository
    repoURL: https://groundhog2k.github.io/helm-charts/
    chart: redis
    targetRevision: 2.4.0
    helm:
      values: |
        # Configuration parameters for Groundhog2k chart
        
        # Disables High Availability (Sentinel setup) for a lightweight single pod
        haMode:
          enabled: false
        
        # Disables Persistent Volume requirements
        persistence:
          enabled: false
          
        # Optional: Configures password authentication (Leave empty or omit if you don't want auth)
        # auth:
        #   password: "myredispassword"
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true