apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        # This tells Prometheus to scrape this pod
        prometheus.io/scrape: "true"
        # The port your application code exposes the /metrics endpoint on
        prometheus.io/port: "8000" 
        # The path where your app serves metrics
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: auth
        image: index.docker.io/himanshusarma123/auth:v5
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: default          # Keep it in the same namespace as your app
  labels:
    # CRITICAL: This label MUST match the release name of your prometheus stack
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: auth
  endpoints:
  - port: http                
    path: /metrics            
    interval: 10s             
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
---