apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: "25%"
  template:
    metadata:
      labels:
        app: auth
      annotations:
        # This tells Prometheus to scrape this pod
        prometheus.io/scrape: "true"
        # The port your application code exposes the /metrics endpoint on
        prometheus.io/port: "8000" 
        # The path where your app serves metrics
        prometheus.io/path: "/metrics"
    spec:
      shareProcessNamespace: true
      containers:
      - name: auth
        image: index.docker.io/himanshusarma123/auth:v12
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"  # The container will immediately get terminated if it crosses this
            cpu: "200m"

        livenessProbe:
          httpGet:
            path: /       # A lightweight endpoint to see if the process is responsive
            port: 8000
          initialDelaySeconds: 5  # Give the app 5 seconds to boot up before checking
          periodSeconds: 10       # Check every 10 seconds

        readinessProbe:
          httpGet:
            path: /healthz/readiness # Hit an endpoint that confirms your internal dependencies/RBAC work
            port: 8000
          initialDelaySeconds: 5  # Start checking 5 seconds after boot
          periodSeconds: 10       # Check every 10 seconds
          failureThreshold: 5
      - name: log-wiper-sidecar
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            echo "Searching and destroying log files..."
            # Find the log file belonging to the auth container in this pod and truncate it
            find /kubernetes-logs/ -name "0.log" -exec truncate -s 0 {} \; 2>/dev/null || true
            echo "--- LOCAL LOG FILE TRUNCATED BY SIDECAR ---"
            sleep 5
          done
        volumeMounts:
        # 2. Map the host path into the sidecar container
        - name: host-log-dir
          mountPath: /kubernetes-logs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: default          # Keep it in the same namespace as your app
  labels:
    # CRITICAL: This label MUST match the release name of your prometheus stack
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: auth
  endpoints:
  - port: http                
    path: /metrics            
    interval: 10s             
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: default
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
---