apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: db-pv
  storageClassName: ""